# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - id: uppercase
          uses: ./
          with:
            text: Hello, World!
      - name: Print converted text
        run: echo "${{ steps.uppercase.outputs.uppercase-text }}"
